### ISSUE TITLE
Add signing of published OCI images with cosign

### ISSUE THREAD

**Issue by devantler** [devantler-tech/platform#819]
### Description

The published Homelab OCI images should be signed with cosign as part of the `publish.yaml` pipeline.

Avisi Cloud provides [a guide](https://github.com/avisi-cloud/cosign-tutorial) for the purpose

### Tasklist

- [x] devantler-tech/.github#9
- [x] devantler-tech/platform#820
- [x] devantler-tech/platform#821
