### ISSUE TITLE
Create a Repo for Backstage and set it up in `devantler/homelab`

### ISSUE THREAD

**Issue by devantler** [devantler-tech/platform#823]
**Tasklist:**

- [ ] devantler-tech/platform#824
- [ ] devantler-tech/platform#825
- [x] devantler-tech/issue-tracker#42
- [x] devantler-tech/issue-tracker#43
